export const tenants = [
  {
    name: "Tony Micelli",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 200,000",
    status: "Paid",
    date: "Oct 1, 2025",
  },
  {
    name: "Woody Boyd",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 220,000",
    status: "Late",
    date: "Oct 21, 2025",
  },
  {
    name: "Willie Tanner",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 250,000",
    status: "Paid",
    date: "Oct 11, 2025",
  },
  {
    name: "Al Bundy",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 200,000",
    status: "Paid",
    date: "Oct 5, 2025",
  },
  {
    name: "April Curtis",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 230,000",
    status: "Late",
    date: "Oct 8, 2025",
  },
  {
    name: "April Curtis",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 230,000",
    status: "Paid",
    date: "Oct 8, 2025",
  },
  {
    name: "April Curtis",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 230,000",
    status: "Paid",
    date: "Oct 8, 2025",
  },
  {
    name: "April Curtis",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 230,000",
    status: "Paid",
    date: "Oct 8, 2025",
  },
  {
    name: "April Curtis",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 230,000",
    status: "Paid",
    date: "Oct 8, 2025",
  },
  {
    name: "April Curtis",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 230,000",
    status: "Late",
    date: "Oct 8, 2025",
  },
  {
    name: "April Curtis",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 230,000",
    status: "Paid",
    date: "Oct 8, 2025",
  },
  {
    name: "April Curtis",
    unit: "Room 101 - Kigali Heights",
    amount: "RF 230,000",
    status: "Paid",
    date: "Oct 8, 2025",
  },
];
